name: Ping Render Backend

on:
  schedule:
    - cron: '30-59/5 2 * * *'
    - cron: '*/5 3-8 * * *'
    - cron: '0-25/5 9 * * *'
    - cron: '30-59 9 * * *'
    - cron: '* 10 * * *'
    - cron: '30-59/5 10 * * *'
    - cron: '*/5 11-15 * * *'
    - cron: '0-25/5 16 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend /ping endpoint
        run: curl -fsSL https://burg-uu6y.onrender.com/ping || echo "Ping failed"
